spring:
  # active mq support.
  activemq:
    in-memory: false
    pool:
      enabled: true
      max-connections: 100
    broker-url: tcp://localhost:61616
    send-timeout: 3000
    close-timeout: 5000
    packages:
      trust-all: true
  freemarker:
    template-loader-path: classpath:/templates/
    charset: UTF-8

server:
  port: 8001
  context-path: /jschedule
  session:
    timeout: 450
    cookie:
      http-only: true
  compression:
    enabled: true
#    datasource:
#      continue-on-error: true
#      driver-class-name: com.mysql.jdbc.Driver
#      username: root
#      password: root
#      url: jdbc:mysql://localhost:3306/jsche?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&createDatabaseIfNotExist=true