spring:
  activemq:
    in-memory: false
    pool:
      enabled: true
      max-connections: 100
    broker-url: tcp://localhost:61616
    send-timeout: 3000
    close-timeout: 5000
    packages:
      trust-all: true